# Generated by Django 4.0.2 on 2022-02-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_melissa_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Melissa_info',
        ),
    ]
