# Generated by Django 4.0.2 on 2022-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Melissa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
